GET {{tsurl}}/metadata?mode=terminology

>>! local-ts1-examples/mode_terminology.json


### http://loinc.org: LA19852-5
GET {{tsurl}}/CodeSystem/$validate-code?code=LA19852-5&url=http://loinc.org

### 2 = icd 10 code: A00  Cholera
GET {{tsurl}}/CodeSystem/2/$validate-code?code=A00


###
GET {{tsurl}}/CodeSystem/loinc/$lookup?code=1963-8

